### ISSUE TITLE
Feat: Consolidate Ginkgo Reports for multiple Test Suites as a single Test Run.

### ISSUE THREAD

**Issue by gowtham-ra** [guidewire-oss/fern-ginkgo-client#11]
**Context:**
In the initial design of the Fern Ginkgo client, we assumed the test suite configuration would reside at the root level of a project. However, Ginkgo's recommended practice is to have a test suite for each package.

Following this approach, now fern-ginkgo client's Report method is used to report from each test suite individually for a single test run. As a result, we end up with multiple test run entries, each corresponding to a different test suite. 

This issue aims to aggregate all the reports from individual test suites and treat them collectively as a single test run.

**Comment by gowtham-ra** [comment]
PFA two files for reference:
1. [Report Single Suite](https://github.com/user-attachments/files/17032169/report-single-suite.json) - Old Way with 1 parent-level test suite for all spec runs.
2. [Report Multiple Suite](https://github.com/user-attachments/files/17032167/report-multi-suite.json) - New Way with multiple test suites (from each pkg) for a single test run

**Comment by mailprak** [comment]
Changes made to : 
https://github.com/mailprak/fern-ginkgo-client-mailprak/tree/feat/consolidate-gnko-report
Updated the file : 
tests/adder_test.go

Todo : 
Test the flow and see how the results are sent to the server

**Comment by mailprak** [comment]
In progress : Issues with displaying report in server page. Continuing to work on this.

**Comment by mailprak** [comment]
The updates for  client is in my forked repo below :

https://github.com/mailprak/fern-ginkgo-client-mailprak/tree/feature/consolidatesuits
branch : feature/consolidatesuits

commit : 
https://github.com/guidewire-oss/fern-ginkgo-client/commit/0d92368a55fec43ac4ae60bae738ff01be6b24ee

Todo : 
To test before creating a PR for main

**Comment by gowtham-ra** [comment]
There is a more straightforward way to solve this issue, which is implemented in the fern-reporter. A new [issue](https://github.com/guidewire-oss/fern-reporter/issues/167) is created in the fern-reporter. So this issue can be closed.
